[package]
name = "nix_crypto_core"
version = "0.1.0"
edition = "2024"

[dependencies]
age = { version = "0.11", features = ["armor"] }
cxx = "1.0"
openssl = "0.10"
sled = "0.34"
regex = "1.12.2"
time = { version = "0.3.44", features = ["parsing"] }
