[package]
name = "nix-crypto"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
age = { version = "0.11", features = ["armor"] }
libc = "0.2"
openssl = "0.10"
cxx = "1.0"
ctor = "0.2"

[build-dependencies]
cxx-build = "1.0"
